import gym
from gym import error, spaces, utils
from gym.utils import seeding

class CotcEnvEasySolo(gym.Env):

  def __init__(self):
    ...
  def step(self, action):
    ...
  def reset(self):
    ...
  def render(self, mode='human'):
    ...
  def close(self):
    ...